services:
  bot:
    container_name: bot

    build:
      context: ./bot/src

    image: bot

    env_file:
      - .env

    depends_on:
      danil-minbetov-db:
        condition: service_healthy

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      
      BOT_DB_USER: ${BOT_DB_USER}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
      BOT_DB_HOST: ${BOT_DB_HOST}
      BOT_DB_PORT: ${BOT_DB_PORT}
      BOT_DB_NAME: ${BOT_DB_NAME}

  danil-minbetov-db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: ${BOT_DB_NAME}
    volumes:
      - danil-minbetov-db:/var/lib/mysql
      - ./mysql/init/danil-minbetov-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3310:3306"

volumes:
  danil-minbetov-db: