services:
  daniil-minbetov-bot:
    container_name: daniil-minbetov-bot

    build:
      context: ./bot/src

    image: daniil-minbetov-bot

    env_file:
      - .env

    depends_on:
      daniil-minbetov-db:
        condition: service_healthy

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      
      BOT_DB_USER: ${BOT_DB_USER}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
      BOT_DB_HOST: ${BOT_DB_HOST}
      BOT_DB_PORT: ${BOT_DB_PORT}
      BOT_DB_NAME: ${BOT_DB_NAME}

  daniil-minbetov-db:
    container_name: daniil-minbetov-db
    image: mysql:8.0

    restart: always

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: ${BOT_DB_NAME}

    volumes:
      - daniil-minbetov-db:/var/lib/mysql
      - ./mysql/init/daniil-minbetov-db:/docker-entrypoint-initdb.d/

    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-p${BOT_DB_PASSWORD}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

    ports:
      - "3310:3306"

volumes:
  daniil-minbetov-db: